import { WorkflowStep, WorkflowStepMeta } from './types';

export const WORKFLOW_STEPS: WorkflowStepMeta[] = [
  {
    id: 'specify',
    number: 1,
    name: 'Specify',
    command: 'spec-linear specify',
    nextStep: 'clarify',
    nextCommandTemplate: 'spec-linear clarify {issueKey}',
    description: 'Synthesizes problem statements, user stories, goals, and boundaries into a formal PRD specification.',
    readsFrom: 'Linear Issue Description / Prompt',
    writesTo: 'Versioned Linear Comment',
    iconName: 'FileText',
  },
  {
    id: 'clarify',
    number: 2,
    name: 'Clarify',
    command: 'spec-linear clarify',
    nextStep: 'analyze',
    nextCommandTemplate: 'spec-linear analyze {issueKey}',
    description: 'Uncovers edge cases, clarifies ambiguities, and locks in concrete architectural decisions.',
    readsFrom: 'Linear Issue + Latest Spec Comment',
    writesTo: 'Versioned Linear Comment',
    iconName: 'HelpCircle',
  },
  {
    id: 'analyze',
    number: 3,
    name: 'Analyze',
    command: 'spec-linear analyze',
    nextStep: 'plan',
    nextCommandTemplate: 'spec-linear plan {issueKey}',
    description: 'Examines system architecture, schema updates, API contracts, security, and performance tradeoffs.',
    readsFrom: 'Linear Issue + Clarifications Comment',
    writesTo: 'Versioned Linear Comment',
    iconName: 'Cpu',
  },
  {
    id: 'plan',
    number: 4,
    name: 'Plan',
    command: 'spec-linear plan',
    nextStep: 'checklist',
    nextCommandTemplate: 'spec-linear checklist {issueKey}',
    description: 'Builds a phased implementation roadmap, zero-downtime migrations, and rollback safeguards.',
    readsFrom: 'Linear Issue + Technical Analysis Comment',
    writesTo: 'Versioned Linear Comment',
    iconName: 'CalendarRange',
  },
  {
    id: 'checklist',
    number: 5,
    name: 'Checklist',
    command: 'spec-linear checklist',
    nextStep: 'tasks',
    nextCommandTemplate: 'spec-linear tasks {issueKey}',
    description: 'Generates exhaustive acceptance criteria, test matrices, and QA verification gates.',
    readsFrom: 'Linear Issue + Plan Comment',
    writesTo: 'Versioned Linear Comment',
    iconName: 'CheckSquare',
  },
  {
    id: 'tasks',
    number: 6,
    name: 'Tasks',
    command: 'spec-linear tasks',
    nextStep: 'implement',
    nextCommandTemplate: 'spec-linear implement {firstChildKey}',
    description: 'Decomposes plan into atomic sub-tasks, creates child issues in Linear, and captures branch names.',
    readsFrom: 'Linear Issue + Checklist Comment',
    writesTo: 'Linear Child Issues + Summary Comment',
    iconName: 'ListOrdered',
    createsChildIssues: true,
  },
  {
    id: 'implement',
    number: 7,
    name: 'Implement',
    command: 'spec-linear implement',
    nextStep: null,
    nextCommandTemplate: '',
    description: 'Creates git branch ONLY now using the child task branchName, and guides focused development.',
    readsFrom: 'Linear Child Issue',
    writesTo: 'Git Branch Activation & Code Guide',
    iconName: 'GitBranch',
    createsBranch: true,
  },
];

export const STEP_DISPLAY_NAMES: Record<WorkflowStep, string> = {
  specify: 'Specification',
  clarify: 'Clarifications',
  analyze: 'Technical Analysis',
  plan: 'Implementation Plan',
  checklist: 'Quality Checklist',
  tasks: 'Execution Tasks & Child Issues',
  implement: 'Implementation Guide',
};
